# Generated by Django 4.1.3 on 2022-11-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.IntegerField()),
                ('author_username', models.CharField(max_length=20, unique=True, verbose_name='title')),
                ('content', models.CharField(max_length=10000, null=True, verbose_name='text content')),
                ('score', models.IntegerField()),
            ],
        ),
    ]
