# Generated by Django 4.1.3 on 2022-11-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_username',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author_username',
            field=models.CharField(max_length=20, verbose_name='author username'),
        ),
    ]
